from .usuario_serializer import *
from .categoria_serializer import *
from .tecnico_serializer import *
from .tecnico_categoria_serializer import *
from .foto_trabajo_serializer import *
from .solicitud_serializer import *
from .foto_solicitud_serializer import *
from .distrito_serializer import *
from .distrito_tecnico_serializer import *
