# Generated by Django 5.2.1 on 2025-05-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnico',
            name='fecha_fin_suscripcion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='fecha_inicio_suscripcion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='mercadopago_collector_id',
            field=models.CharField(blank=True, help_text='ID del pagador en Mercado Pago', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='mercadopago_preference_id',
            field=models.CharField(blank=True, help_text='ID de la preferencia de pago de Mercado Pago', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='suscripcion_activa',
            field=models.BooleanField(default=False),
        ),
    ]
