# Generated by Django 5.2.1 on 2025-06-14 02:22

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tecnico_fecha_fin_suscripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='descripcion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='titulo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='foto_perfil',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
