from .usuario_model import *
from .categoria_model import *
from .tecnico_model import *
from .tecnico_categoria_model import *
from .foto_trabajo_model import *
from .solicitud_model import *
from .foto_solicitud_model import *
from .distrito_model import *
from .distrito_tecnico_model import *
